[web]
ip = "0.0.0.0"
port = 6543

[stats]
rosters_interval = 3000
players_interval = 172800
users_interval = 3000
leagues_interval = 3000
state_interval = 3000
matchups_interval = 3000
dev_mode = true
players_path = "data/players.json"

[database]
host = "0.0.0.0"
port = 5432
user = "admin"
password = "password"
dbname = "bigleague"
max_open = 32
max_idle = 8
timeout = 15

[bigleague]
leagues = []
playoffs_start_week = 10
playoffs_championship_week = 12

# Only one of the following playoff options are supported

# Gives bids to the top teams regardless of which league they are in
playoffs_at_large = { bids = 4 }

# Gives bids to the top n teams in each league
# This is currently unsupported!
playoffs_per_league = { bids_per_league = 2 }
