[web]
ip = "127.0.0.1"
port = 8000

[stats]
rosters_interval = 3000
players_interval = 172800
users_interval = 3000
leagues_interval = 3000
state_interval = 3000
matchups_interval = 3000
dev_mode = true
players_path = "data/players.json"

[database]
host = "0.0.0.0"
port = 5432
user = "admin"
password = "password"
dbname = "bigleague"
max_open = 32
max_idle = 8
timeout = 15

[bigleague]
leagues = []
playoff_teams = 8
playoff_start_week = 14
